/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package realisasiprokerGUI;

import com.placeholder.PlaceHolder;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import realisasiproker.DatabaseMySQL;

/**
 *
 * @author VINORIOUS
 */
public class Cetak extends javax.swing.JFrame {

    /**
     * Creates new form Cetak
     */
    public Cetak() {
        initComponents();
        AturKolomTabelRealisasi();
        joinprokerreal();
        placeholder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_cetak = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbl_Realisasi = new javax.swing.JTable();
        btn_refresh = new javax.swing.JButton();
        jDate_tglawal = new com.toedter.calendar.JDateChooser();
        jDate_tglakhir = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        btn_cetakperiode = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cetak Realisasi");
        setName("Cetak Realisasi"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cetak.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_cetak.setText("Cetak");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 100, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cetak Sebagian :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, 30));

        jTbl_Realisasi.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 0)));
        jTbl_Realisasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "User ID", "Uraian Proker", "Tanggal Proker", "Dosen", "Tanggal Realisasi", "Anggaran", "Deskripsi", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbl_Realisasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbl_RealisasiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTbl_Realisasi);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 410));

        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/realisasiprokerGUI/image/Refresh.png"))); // NOI18N
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jPanel1.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 50, 30));
        jPanel1.add(jDate_tglawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 160, 30));
        jPanel1.add(jDate_tglakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("KE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, 30));

        btn_cetakperiode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_cetakperiode.setText("Cari");
        btn_cetakperiode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakperiodeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cetakperiode, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void AturKolomTabelRealisasi(){
        jTbl_Realisasi.setAutoResizeMode(jTbl_Realisasi.AUTO_RESIZE_OFF);
        TableColumn col = jTbl_Realisasi.getColumnModel().getColumn(0);
        col.setPreferredWidth(30);
        col = jTbl_Realisasi.getColumnModel().getColumn(1);
        col.setPreferredWidth(53);
        col = jTbl_Realisasi.getColumnModel().getColumn(2);
        col.setPreferredWidth(232);
        col = jTbl_Realisasi.getColumnModel().getColumn(3);
        col.setPreferredWidth(102);
        col = jTbl_Realisasi.getColumnModel().getColumn(4);
        col.setPreferredWidth(171);
        col = jTbl_Realisasi.getColumnModel().getColumn(5);
        col.setPreferredWidth(118);
        col = jTbl_Realisasi.getColumnModel().getColumn(6);
        col.setPreferredWidth(93);
        col = jTbl_Realisasi.getColumnModel().getColumn(7);
        col.setPreferredWidth(180);
        col = jTbl_Realisasi.getColumnModel().getColumn(8);
        col.setPreferredWidth(77);
    
    }
    
    public void refresh(){
        DefaultTableModel model = (DefaultTableModel) jTbl_Realisasi.getModel();
        while (model.getRowCount() > 0) {
            model.setRowCount(0);
        }
        Object[] atributreal = new Object[9];
        try {

            String query = "select realisasi.id_laporan, realisasi.id_user, proker.uraian_proker, proker.tglperencanaan_proker, proker.Dosen_penanggung, realisasi.tglRealisasi, realisasi.anggaran, realisasi.deskripsi_laporan, realisasi.Status from realisasi inner join proker on realisasi.id_proker = proker.id_proker order by realisasi.id_laporan ASC";
            PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query);
            ResultSet rs = statement.executeQuery();

            while (rs.next()) {
                atributreal[0] = rs.getInt("realisasi.id_laporan");
                atributreal[1] = rs.getInt("realisasi.id_user");
                atributreal[2] = rs.getString("proker.uraian_proker");
                atributreal[3] = rs.getString("proker.tglperencanaan_proker");
                atributreal[4] = rs.getString("proker.Dosen_penanggung");
                atributreal[5] = rs.getString("realisasi.tglRealisasi");
                atributreal[6] = rs.getDouble("realisasi.anggaran");
                atributreal[7] = rs.getString("realisasi.deskripsi_laporan");
                atributreal[8] = rs.getString("realisasi.Status");

                model.addRow(atributreal);
            }
            jTbl_Realisasi.setModel(model);
            statement.close();
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    
    }
    
//     public void joinprokerrealCari() {
//        
//        DefaultTableModel model = (DefaultTableModel) jTbl_Realisasi.getModel();
//        while (model.getRowCount() > 0) {
//            model.setRowCount(0);
//        }
//        Object[] atributreal = new Object[9];
//        try {
//
//            String query = "select realisasi.id_laporan, realisasi.id_user, proker.uraian_proker, proker.tglperencanaan_proker, proker.Dosen_penanggung, realisasi.tglRealisasi, realisasi.anggaran, realisasi.deskripsi_laporan, realisasi.Status from realisasi inner join proker on realisasi.id_proker = proker.id_proker where realisasi.id_laporan='" + txt_cetak.getText() + "'";
//            PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query);
//            ResultSet rs = statement.executeQuery();
//
//            while (rs.next()) {
//                atributreal[0] = rs.getInt("realisasi.id_laporan");
//                atributreal[1] = rs.getInt("realisasi.id_user");
//                atributreal[2] = rs.getString("proker.uraian_proker");
//                atributreal[3] = rs.getString("proker.tglperencanaan_proker");
//                atributreal[4] = rs.getString("proker.Dosen_penanggung");
//                atributreal[5] = rs.getString("realisasi.tglRealisasi");
//                atributreal[6] = rs.getDouble("realisasi.anggaran");
//                atributreal[7] = rs.getString("realisasi.deskripsi_laporan");
//                atributreal[8] = rs.getString("realisasi.Status");
//
//                model.addRow(atributreal);
//            }
//            jTbl_Realisasi.setModel(model);
//            statement.close();
//            rs.close();
//        } catch (Exception ex) {
//            System.out.println(ex.getMessage());
//        }
//
//    }
    
    public void joinprokerreal () {
        DefaultTableModel model = (DefaultTableModel) jTbl_Realisasi.getModel();
        Object[] atributreal = new Object[9];
        try {

            String query = "select realisasi.id_laporan, realisasi.id_user, proker.uraian_proker, proker.tglperencanaan_proker, proker.Dosen_penanggung, realisasi.tglRealisasi, realisasi.anggaran, realisasi.deskripsi_laporan, realisasi.Status from realisasi inner join proker on realisasi.id_proker = proker.id_proker order by realisasi.id_laporan ASC";
            PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query);
            ResultSet rs = statement.executeQuery();

            while (rs.next()) {
                atributreal[0] = rs.getInt("realisasi.id_laporan");
                atributreal[1] = rs.getInt("realisasi.id_user");
                atributreal[2] = rs.getString("proker.uraian_proker");
                atributreal[3] = rs.getString("proker.tglperencanaan_proker");
                atributreal[4] = rs.getString("proker.Dosen_penanggung");
                atributreal[5] = rs.getString("realisasi.tglRealisasi");
                atributreal[6] = rs.getDouble("realisasi.anggaran");
                atributreal[7] = rs.getString("realisasi.deskripsi_laporan");
                atributreal[8] = rs.getString("realisasi.Status");

                model.addRow(atributreal);
            }
            jTbl_Realisasi.setModel(model);
            statement.close();
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }
    
    public void joinprokerperiode(){
        String format="yyyy-MM-dd";
        SimpleDateFormat date= new SimpleDateFormat(format);
        String tglawal,tglakhir;
        tglawal = (String.valueOf(date.format(jDate_tglawal.getDate())));
        tglakhir = (String.valueOf(date.format(jDate_tglakhir.getDate())));

        DefaultTableModel model = (DefaultTableModel) jTbl_Realisasi.getModel();
        while (model.getRowCount() > 0) {
            model.setRowCount(0);
        }
        Object[] atributreal = new Object[9];
        try {

            String query = "select realisasi.id_laporan, realisasi.id_user, proker.uraian_proker, proker.tglperencanaan_proker, proker.Dosen_penanggung, realisasi.tglRealisasi, realisasi.anggaran, realisasi.deskripsi_laporan, realisasi.Status from realisasi inner join proker on realisasi.id_proker = proker.id_proker where realisasi.tglRealisasi between '"+tglawal+"' and '"+tglakhir+"'";
            PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query);
            ResultSet rs = statement.executeQuery();

            while (rs.next()) {
                atributreal[0] = rs.getInt("realisasi.id_laporan");
                atributreal[1] = rs.getInt("realisasi.id_user");
                atributreal[2] = rs.getString("proker.uraian_proker");
                atributreal[3] = rs.getString("proker.tglperencanaan_proker");
                atributreal[4] = rs.getString("proker.Dosen_penanggung");
                atributreal[5] = rs.getString("realisasi.tglRealisasi");
                atributreal[6] = rs.getDouble("realisasi.anggaran");
                atributreal[7] = rs.getString("realisasi.deskripsi_laporan");
                atributreal[8] = rs.getString("realisasi.Status");

                model.addRow(atributreal);
            }
            jTbl_Realisasi.setModel(model);
            statement.close();
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
    private void jTbl_RealisasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_RealisasiMouseClicked

    }//GEN-LAST:event_jTbl_RealisasiMouseClicked

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        MessageFormat header = new MessageFormat("Data Realisasi Proker");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
 
        try{
            jTbl_Realisasi.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        }
        catch (java.awt.print.PrinterException e){
        System.err.format("Cannot print %s%n", e.getMessage());
                }
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        refresh();
    }//GEN-LAST:event_btn_refreshActionPerformed

    public void placeholder() {
//        PlaceHolder holder1 = new PlaceHolder(txt_cetak, "Masukkan No.");

    }
    
    private void btn_cetakperiodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakperiodeActionPerformed

        joinprokerperiode();
        
    }//GEN-LAST:event_btn_cetakperiodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cetak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_cetakperiode;
    private javax.swing.JButton btn_refresh;
    private com.toedter.calendar.JDateChooser jDate_tglakhir;
    private com.toedter.calendar.JDateChooser jDate_tglawal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTbl_Realisasi;
    // End of variables declaration//GEN-END:variables
}
