/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package realisasiprokerGUI;

import com.placeholder.PlaceHolder;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import realisasiproker.DatabaseMySQL;
import realisasiproker.Realisasi;
import realisasiproker.Proker;
import realisasiproker.Realisasi;
import realisasiproker.User;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import realisasiproker.Dosen;
import java.text.*;
import java.awt.print.*;
import javax.swing.JTable;
import javax.swing.table.TableColumn;

/**
 *
 * @author ASUS
 */
public class Menu_Prodi extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Prodi
     */
    public Menu_Prodi() {
        initComponents();
        User_Info.setVisible(false);
        prodi_proker.setVisible(false);
        prodi_Realisasi.setVisible(false);
        User u = new User();
        lb_iduser.setText(String.valueOf(u.getID()));
        showNamaUser();
        tampilproker();
        tampilprokerstatus();
        tampildosen();
        tampiluserpass();
        autonumberIdRealisasi();
        AturKolomTabelRealisasi();
        AturKolomTabelProker();
        AturKolomTabelProkerReal();
        placeholder();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panelUtama = new javax.swing.JPanel();
        panelMENU = new javax.swing.JPanel();
        PanelUser = new javax.swing.JPanel();
        lb_nama = new javax.swing.JLabel();
        button_infoUser = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JPanel();
        LOGOUT_BUTTON = new javax.swing.JLabel();
        panelDataProker = new javax.swing.JPanel();
        button_DataProker = new javax.swing.JLabel();
        panelDataRealisasi1 = new javax.swing.JPanel();
        button_DataRealisasi = new javax.swing.JLabel();
        logoUnitomo = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        panelisi = new javax.swing.JPanel();
        User_Info = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Panel_detailinfo = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        pass = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        id_dosen = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nama_dosen = new javax.swing.JTextField();
        npp = new javax.swing.JTextField();
        ttl = new javax.swing.JTextField();
        agama = new javax.swing.JTextField();
        jekel = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        delete_info_akun = new javax.swing.JButton();
        edit_info_akun = new javax.swing.JButton();
        prodi_proker = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTbl_Proker1 = new javax.swing.JTable();
        txt_cariproker = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btn_viewall = new javax.swing.JButton();
        btn_printp = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        panelSelamatDatang = new javax.swing.JPanel();
        SelamatDatang = new javax.swing.JLabel();
        di = new javax.swing.JLabel();
        MenuProdi = new javax.swing.JLabel();
        prodi_Realisasi = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        deskripsi = new javax.swing.JTextArea();
        PanelTutup = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idproker = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_Proker = new javax.swing.JTable();
        idrealisasi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbl_Realisasi = new javax.swing.JTable();
        jdatetanggal = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        anggaran = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cb_status = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        btn_cetak = new javax.swing.JButton();
        txt_realprodi = new javax.swing.JTextField();
        btn_shortingprodi = new javax.swing.JButton();
        jDate_tglawalproker = new com.toedter.calendar.JDateChooser();
        jDate_tglakhirproker = new com.toedter.calendar.JDateChooser();
        BTN_cariprokerperiode = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jDate_tglawalreal = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        jDate_tglakhirreal = new com.toedter.calendar.JDateChooser();
        BTN_carirealperiode = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMENU.setBackground(new java.awt.Color(0, 204, 204));
        panelMENU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelUser.setBackground(new java.awt.Color(0, 204, 204));
        PanelUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_nama.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_nama.setForeground(new java.awt.Color(255, 255, 255));
        lb_nama.setText(" ");
        lb_nama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelUser.add(lb_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 260, 60));

        button_infoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/realisasiprokerGUI/image/MENUUSER.png"))); // NOI18N
        button_infoUser.setText("jLabel3");
        button_infoUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_infoUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_infoUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_infoUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_infoUserMouseExited(evt);
            }
        });
        PanelUser.add(button_infoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 60));

        lb_iduser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_iduser.setForeground(new java.awt.Color(255, 255, 255));
        PanelUser.add(lb_iduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 70, 20));

        panelMENU.add(PanelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 330, 70));

        LOGOUT.setBackground(new java.awt.Color(0, 204, 204));
        LOGOUT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGOUT_BUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/realisasiprokerGUI/image/LOGOUT.png"))); // NOI18N
        LOGOUT_BUTTON.setText("jLabel6");
        LOGOUT_BUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOGOUT_BUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOUT_BUTTONMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LOGOUT_BUTTONMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LOGOUT_BUTTONMouseExited(evt);
            }
        });
        LOGOUT.add(LOGOUT_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 60));

        panelMENU.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 330, 70));

        panelDataProker.setBackground(new java.awt.Color(0, 204, 204));
        panelDataProker.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_DataProker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/realisasiprokerGUI/image/DATAPROKER.png"))); // NOI18N
        button_DataProker.setText("jLabel1");
        button_DataProker.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_DataProker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_DataProkerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_DataProkerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_DataProkerMouseExited(evt);
            }
        });
        panelDataProker.add(button_DataProker, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 60));

        panelMENU.add(panelDataProker, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 330, 70));

        panelDataRealisasi1.setBackground(new java.awt.Color(0, 204, 204));
        panelDataRealisasi1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_DataRealisasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/realisasiprokerGUI/image/DATAREALISASI.png"))); // NOI18N
        button_DataRealisasi.setText("jLabel1");
        button_DataRealisasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_DataRealisasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_DataRealisasiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_DataRealisasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_DataRealisasiMouseExited(evt);
            }
        });
        panelDataRealisasi1.add(button_DataRealisasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 60));

        panelMENU.add(panelDataRealisasi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 330, 70));

        logoUnitomo.setBackground(new java.awt.Color(0, 204, 204));
        logoUnitomo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/realisasiprokerGUI/image/LOGOUNITOMO.png"))); // NOI18N
        LOGO.setText("jLabel1");
        LOGO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOGO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOMouseClicked(evt);
            }
        });
        logoUnitomo.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 160));

        panelMENU.add(logoUnitomo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 150, 160));

        panelUtama.add(panelMENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 640));

        panelisi.setBackground(new java.awt.Color(0, 0, 51));
        panelisi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        User_Info.setBackground(new java.awt.Color(0, 0, 51));
        User_Info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("INFO USER");
        User_Info.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        Panel_detailinfo.setBackground(new java.awt.Color(0, 0, 51));
        Panel_detailinfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        Panel_detailinfo.setForeground(new java.awt.Color(255, 255, 255));
        Panel_detailinfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Panel_detailinfo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 210, 10));
        Panel_detailinfo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 210, 10));
        Panel_detailinfo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 210, 10));
        Panel_detailinfo.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 210, 10));
        Panel_detailinfo.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 210, 10));
        Panel_detailinfo.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 210, 10));
        Panel_detailinfo.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 210, 10));
        Panel_detailinfo.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 210, 10));

        pass.setBackground(new java.awt.Color(0, 0, 51));
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Panel_detailinfo.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 210, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password      :");
        Panel_detailinfo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID                :");
        Panel_detailinfo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, 30));

        id_dosen.setBackground(new java.awt.Color(0, 0, 51));
        id_dosen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id_dosen.setForeground(new java.awt.Color(255, 255, 255));
        id_dosen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        id_dosen.setFocusable(false);
        Panel_detailinfo.add(id_dosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 210, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nama Dosen  :");
        Panel_detailinfo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("NPP              :");
        Panel_detailinfo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tanggal Lahir :");
        Panel_detailinfo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Agama          :");
        Panel_detailinfo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Jenis Kelamin :");
        Panel_detailinfo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Username      :");
        Panel_detailinfo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        nama_dosen.setBackground(new java.awt.Color(0, 0, 51));
        nama_dosen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nama_dosen.setForeground(new java.awt.Color(255, 255, 255));
        nama_dosen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Panel_detailinfo.add(nama_dosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 210, 30));

        npp.setBackground(new java.awt.Color(0, 0, 51));
        npp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        npp.setForeground(new java.awt.Color(255, 255, 255));
        npp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Panel_detailinfo.add(npp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 210, 30));

        ttl.setBackground(new java.awt.Color(0, 0, 51));
        ttl.setForeground(new java.awt.Color(255, 255, 255));
        ttl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Panel_detailinfo.add(ttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 210, 30));

        agama.setBackground(new java.awt.Color(0, 0, 51));
        agama.setForeground(new java.awt.Color(255, 255, 255));
        agama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Panel_detailinfo.add(agama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 210, 30));

        jekel.setBackground(new java.awt.Color(0, 0, 51));
        jekel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jekel.setForeground(new java.awt.Color(255, 255, 255));
        jekel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Panel_detailinfo.add(jekel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 210, 30));

        username.setBackground(new java.awt.Color(0, 0, 51));
        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Panel_detailinfo.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 210, 30));

        delete_info_akun.setText("Delete");
        delete_info_akun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_info_akunActionPerformed(evt);
            }
        });
        Panel_detailinfo.add(delete_info_akun, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 80, -1));

        edit_info_akun.setText("Edit Akun");
        edit_info_akun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_info_akunActionPerformed(evt);
            }
        });
        Panel_detailinfo.add(edit_info_akun, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 80, -1));

        User_Info.add(Panel_detailinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 530, 490));

        panelisi.add(User_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        prodi_proker.setBackground(new java.awt.Color(0, 0, 51));
        prodi_proker.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTbl_Proker1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 0)));
        jTbl_Proker1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTbl_Proker1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Proker", "Dosen Penanggung", "Uraian Proker", "Status Proker", "Anggaran Dana", "Tanggal "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTbl_Proker1);

        prodi_proker.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 880, 510));

        txt_cariproker.setToolTipText("Tekan \"Enter\" untuk prosess");
        txt_cariproker.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cariprokerKeyPressed(evt);
            }
        });
        prodi_proker.add(txt_cariproker, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 190, -1));

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        prodi_proker.add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DAFTAR PENGAJUAN PROKER");
        prodi_proker.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        btn_viewall.setText("View all");
        btn_viewall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewallActionPerformed(evt);
            }
        });
        prodi_proker.add(btn_viewall, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, 30));

        btn_printp.setText("Print");
        btn_printp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printpActionPerformed(evt);
            }
        });
        prodi_proker.add(btn_printp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, 30));

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        prodi_proker.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, 30));

        panelisi.add(prodi_proker, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        panelSelamatDatang.setBackground(new java.awt.Color(0, 0, 51));
        panelSelamatDatang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SelamatDatang.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        SelamatDatang.setForeground(new java.awt.Color(255, 255, 255));
        SelamatDatang.setText("Selamat Datang");
        panelSelamatDatang.add(SelamatDatang, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 205, 403, 69));

        di.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        di.setForeground(new java.awt.Color(255, 255, 255));
        di.setText("di");
        panelSelamatDatang.add(di, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 280, 57, 41));

        MenuProdi.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        MenuProdi.setForeground(new java.awt.Color(255, 255, 255));
        MenuProdi.setText("Menu Prodi");
        panelSelamatDatang.add(MenuProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 339, 287, 53));

        panelisi.add(panelSelamatDatang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        prodi_Realisasi.setBackground(new java.awt.Color(0, 0, 51));
        prodi_Realisasi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        prodi_Realisasi.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 190, 10));
        prodi_Realisasi.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 190, 10));
        prodi_Realisasi.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 190, 10));
        prodi_Realisasi.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 190, 10));
        prodi_Realisasi.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 190, 10));

        deskripsi.setBackground(new java.awt.Color(0, 0, 51));
        deskripsi.setColumns(20);
        deskripsi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deskripsi.setForeground(new java.awt.Color(255, 255, 255));
        deskripsi.setRows(5);
        deskripsi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setViewportView(deskripsi);

        prodi_Realisasi.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 190, 180));

        PanelTutup.setBackground(new java.awt.Color(0, 0, 51));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Deskripsi :");

        javax.swing.GroupLayout PanelTutupLayout = new javax.swing.GroupLayout(PanelTutup);
        PanelTutup.setLayout(PanelTutupLayout);
        PanelTutupLayout.setHorizontalGroup(
            PanelTutupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTutupLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
        );
        PanelTutupLayout.setVerticalGroup(
            PanelTutupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTutupLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        prodi_Realisasi.add(PanelTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 200, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM REALISASI PROKER");
        prodi_Realisasi.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Proker :");
        prodi_Realisasi.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 110, -1));

        idproker.setBackground(new java.awt.Color(0, 0, 51));
        idproker.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idproker.setForeground(new java.awt.Color(255, 255, 255));
        idproker.setToolTipText("Tekan \"Enter\" untuk prosess");
        idproker.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        idproker.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idprokerKeyPressed(evt);
            }
        });
        prodi_Realisasi.add(idproker, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 190, 30));

        jTbl_Proker.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 0)));
        jTbl_Proker.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTbl_Proker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Dosen", "Uraian Proker", "Status", "Anggaran", "Tanggal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbl_Proker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbl_ProkerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTbl_Proker);

        prodi_Realisasi.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 620, 210));

        idrealisasi.setBackground(new java.awt.Color(0, 0, 51));
        idrealisasi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idrealisasi.setForeground(new java.awt.Color(255, 255, 255));
        idrealisasi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        idrealisasi.setFocusable(false);
        prodi_Realisasi.add(idrealisasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Realisasi:");
        prodi_Realisasi.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 110, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal Realisasi :");
        prodi_Realisasi.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 160, -1));

        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/realisasiprokerGUI/image/Refresh.png"))); // NOI18N
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        prodi_Realisasi.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 50, 30));

        jTbl_Realisasi.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 0)));
        jTbl_Realisasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "User ID", "Proker ID", "Tanggal Realisasi", "Anggaran", "Deskripsi", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbl_Realisasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbl_RealisasiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTbl_Realisasi);

        prodi_Realisasi.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 620, 210));

        jdatetanggal.setBackground(new java.awt.Color(0, 0, 51));
        jdatetanggal.setForeground(new java.awt.Color(255, 255, 255));
        prodi_Realisasi.add(jdatetanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 190, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Anggaran :");
        prodi_Realisasi.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 110, -1));

        anggaran.setBackground(new java.awt.Color(0, 0, 51));
        anggaran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        anggaran.setForeground(new java.awt.Color(255, 255, 255));
        anggaran.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        prodi_Realisasi.add(anggaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 190, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Status :");
        prodi_Realisasi.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 110, -1));

        cb_status.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        prodi_Realisasi.add(cb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 190, 30));

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        prodi_Realisasi.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 60, -1));

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        prodi_Realisasi.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 60, -1));

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        prodi_Realisasi.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 70, -1));

        btn_cetak.setText("Cetak");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        prodi_Realisasi.add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 190, 40));
        prodi_Realisasi.add(txt_realprodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 50, -1));

        btn_shortingprodi.setText("Cari");
        btn_shortingprodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_shortingprodiActionPerformed(evt);
            }
        });
        prodi_Realisasi.add(btn_shortingprodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 60, 30));
        prodi_Realisasi.add(jDate_tglawalproker, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));
        prodi_Realisasi.add(jDate_tglakhirproker, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        BTN_cariprokerperiode.setText("Cari");
        BTN_cariprokerperiode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_cariprokerperiodeActionPerformed(evt);
            }
        });
        prodi_Realisasi.add(BTN_cariprokerperiode, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, 30));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("KE");
        prodi_Realisasi.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, 20));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Cari Sebagian :");
        prodi_Realisasi.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, 20));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Cari Sebagian :");
        prodi_Realisasi.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, 20));
        prodi_Realisasi.add(jDate_tglawalreal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, -1, -1));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("KE");
        prodi_Realisasi.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, -1, 20));
        prodi_Realisasi.add(jDate_tglakhirreal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, -1, -1));

        BTN_carirealperiode.setText("Cari");
        BTN_carirealperiode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_carirealperiodeActionPerformed(evt);
            }
        });
        prodi_Realisasi.add(BTN_carirealperiode, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, -1, 30));

        panelisi.add(prodi_Realisasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        panelUtama.add(panelisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 920, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1250, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void placeholder() {
        PlaceHolder holder1 = new PlaceHolder(txt_realprodi, "Masukkan ID Realisasi");
        PlaceHolder holder2 = new PlaceHolder(txt_cariproker, "Masukan ID Proker");

    }

    public void AturKolomTabelRealisasi() {
        jTbl_Realisasi.setAutoResizeMode(jTbl_Realisasi.AUTO_RESIZE_OFF);
        TableColumn col = jTbl_Realisasi.getColumnModel().getColumn(0);
        col.setPreferredWidth(30);
        col = jTbl_Realisasi.getColumnModel().getColumn(1);
        col.setPreferredWidth(53);
        col = jTbl_Realisasi.getColumnModel().getColumn(2);
        col.setPreferredWidth(64);
        col = jTbl_Realisasi.getColumnModel().getColumn(3);
        col.setPreferredWidth(116);
        col = jTbl_Realisasi.getColumnModel().getColumn(4);
        col.setPreferredWidth(84);
        col = jTbl_Realisasi.getColumnModel().getColumn(5);
        col.setPreferredWidth(207);
        col = jTbl_Realisasi.getColumnModel().getColumn(6);
        col.setPreferredWidth(63);

    }

    public void AturKolomTabelProker() {
        jTbl_Proker1.setAutoResizeMode(jTbl_Proker1.AUTO_RESIZE_OFF);
        TableColumn col = jTbl_Proker1.getColumnModel().getColumn(0);
        col.setPreferredWidth(65);
        col = jTbl_Proker1.getColumnModel().getColumn(1);
        col.setPreferredWidth(177);
        col = jTbl_Proker1.getColumnModel().getColumn(2);
        col.setPreferredWidth(270);
        col = jTbl_Proker1.getColumnModel().getColumn(3);
        col.setPreferredWidth(168);
        col = jTbl_Proker1.getColumnModel().getColumn(4);
        col.setPreferredWidth(120);
        col = jTbl_Proker1.getColumnModel().getColumn(5);
        col.setPreferredWidth(102);

    }

    public void AturKolomTabelProkerReal() {
        jTbl_Proker.setAutoResizeMode(jTbl_Proker1.AUTO_RESIZE_OFF);
        TableColumn col = jTbl_Proker.getColumnModel().getColumn(0);
        col.setPreferredWidth(25);
        col = jTbl_Proker.getColumnModel().getColumn(1);
        col.setPreferredWidth(146);
        col = jTbl_Proker.getColumnModel().getColumn(2);
        col.setPreferredWidth(233);
        col = jTbl_Proker.getColumnModel().getColumn(3);
        col.setPreferredWidth(65);
        col = jTbl_Proker.getColumnModel().getColumn(4);
        col.setPreferredWidth(72);
        col = jTbl_Proker.getColumnModel().getColumn(5);
        col.setPreferredWidth(79);

    }

    public void tampilRealisasi() {
        Realisasi realisasi2 = new Realisasi();
        DefaultTableModel model = (DefaultTableModel) jTbl_Realisasi.getModel();
        Object[] atributreal = new Object[7];
        try {
            ArrayList tampil = realisasi2.viewSaja(); //harus dikasih try catch
            Iterator listrealisasi = tampil.iterator();

            int i = 0;
            while (i < tampil.size()) {
                Realisasi eachreal;
                eachreal = (Realisasi) listrealisasi.next();
                atributreal[0] = eachreal.getIdLaporan();
                atributreal[1] = eachreal.getIdDariUser();
                atributreal[2] = eachreal.getIdDariProker();
                atributreal[3] = eachreal.getTglRealisasi();
                atributreal[4] = eachreal.getAnggaran();
                atributreal[5] = eachreal.getDeskripsi();
                atributreal[6] = eachreal.getStatus();
                //System.out.println(eachKepsek.getIdKepsek()+"-"+eachKepsek.getNamaKepsek());
                model.addRow(atributreal);
                i++;
            }
            jTbl_Realisasi.setModel(model);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());

        }

    }

    public void carirealprodi() {

        Realisasi real = new Realisasi();
        real.setIdLaporan(Integer.parseInt(txt_realprodi.getText()));
        DefaultTableModel tabelrealwadek = (DefaultTableModel) jTbl_Realisasi.getModel();
        Object[] realwadek = new Object[7];

        try {//eksekusi proker
            ArrayList cari = real.viewCari(); //harus dikasih try catch
            Iterator listproker = cari.iterator();
            //            System.out.println("size: " + prokerAll.size()); //ok
            int i = 0;
            if (i < cari.size()) {
                Realisasi erealwadek;
                erealwadek = (Realisasi) listproker.next();
                realwadek[0] = erealwadek.getIdLaporan();
                realwadek[1] = erealwadek.getIdDariUser();
                realwadek[2] = erealwadek.getIdDariProker();
                realwadek[3] = erealwadek.getTglRealisasi();
                realwadek[4] = erealwadek.getAnggaran();
                realwadek[5] = erealwadek.getDeskripsi();
                realwadek[6] = erealwadek.getStatus();

                tabelrealwadek.addRow(realwadek);
                i++;
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan!!");
            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        jTbl_Realisasi.setModel(tabelrealwadek);

    }

    public void updateUserProkertoRealisasi() throws Exception {
        String query2 = "update realisasi set id_user=?, id_proker=?  where id_laporan=? ";
        PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query2);
        statement.setString(1, lb_iduser.getText());
        statement.setString(2, idproker.getText());
        statement.setString(3, idrealisasi.getText());
        statement.executeUpdate();
        statement.close();
    }

    public void refreshtabel() throws Exception {
        DefaultTableModel model = (DefaultTableModel) jTbl_Realisasi.getModel();
        while (model.getRowCount() > 0) {
            model.setRowCount(0);
        }
        tampilRealisasi();
    }

    public void refreshtabelhistory() throws Exception {
        DefaultTableModel model = (DefaultTableModel) jTbl_Proker.getModel();
        while (model.getRowCount() > 0) {
            model.setRowCount(0);
        }

    }

    public void refreshtabelproker() throws Exception {
        DefaultTableModel model = (DefaultTableModel) jTbl_Proker1.getModel();
        while (model.getRowCount() > 0) {
            model.setRowCount(0);
        }
        cariproker();
        //tampilproker();
    }

    public void editRealisasi() throws Exception {
        String query = "update realisasi set tglRealisasi=?, anggaran=? , deskripsi_laporan=?, Status=? where id_laporan=?";
        PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query);

        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        statement.setString(1, date.format(jdatetanggal.getDate()));
        statement.setString(2, anggaran.getText());
        statement.setString(3, deskripsi.getText());
        statement.setString(4, (String) cb_status.getSelectedItem());
        statement.setString(5, idrealisasi.getText());
        statement.executeUpdate();
        statement.close();

    }

    public void showNamaUser() {
        try {
            String query = "select nama_dosen from dosen where idDosen='" + lb_iduser.getText() + "'";
            PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                lb_nama.setText(rs.getString("nama_dosen"));
            }

            statement.close();
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }

    private void button_infoUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_infoUserMouseClicked
        User_Info.setVisible(true);
        prodi_proker.setVisible(false);
        prodi_Realisasi.setVisible(false);
        panelSelamatDatang.setVisible(false);
    }//GEN-LAST:event_button_infoUserMouseClicked

    private void button_DataProkerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_DataProkerMouseClicked
        prodi_proker.setVisible(true);
        prodi_Realisasi.setVisible(false);
        User_Info.setVisible(false);
        panelSelamatDatang.setVisible(false);
    }//GEN-LAST:event_button_DataProkerMouseClicked

    private void button_DataRealisasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_DataRealisasiMouseClicked
        prodi_Realisasi.setVisible(true);
        User_Info.setVisible(false);
        prodi_proker.setVisible(false);
        panelSelamatDatang.setVisible(false);
    }//GEN-LAST:event_button_DataRealisasiMouseClicked

    private void button_infoUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_infoUserMouseEntered
        PanelUser.setBackground(new Color(0, 0, 51));

    }//GEN-LAST:event_button_infoUserMouseEntered

    private void button_infoUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_infoUserMouseExited
        PanelUser.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_button_infoUserMouseExited

    private void button_DataRealisasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_DataRealisasiMouseEntered
        panelDataRealisasi1.setBackground(new Color(0, 0, 51));

    }//GEN-LAST:event_button_DataRealisasiMouseEntered

    private void button_DataRealisasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_DataRealisasiMouseExited

        panelDataRealisasi1.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_button_DataRealisasiMouseExited

    private void LOGOUT_BUTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUT_BUTTONMouseClicked
        this.dispose();
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_LOGOUT_BUTTONMouseClicked

    private void LOGOUT_BUTTONMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUT_BUTTONMouseEntered
        LOGOUT.setBackground(new Color(0, 0, 51));
    }//GEN-LAST:event_LOGOUT_BUTTONMouseEntered

    private void LOGOUT_BUTTONMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUT_BUTTONMouseExited
        LOGOUT.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_LOGOUT_BUTTONMouseExited

    private void idprokerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idprokerKeyPressed
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            DefaultTableModel model = (DefaultTableModel) jTbl_Proker.getModel();
//            while (model.getRowCount() > 0) {
//                model.setRowCount(0);
//            }
//            
//            Proker proker = new Proker();
//            proker.setIdProker(Integer.parseInt(idproker.getText()));
//            DefaultTableModel tabelproker = (DefaultTableModel) jTbl_Proker.getModel();
//            Object[] atributproker = new Object[5];
//
//            try {//eksekusi proker
//                ArrayList cari = proker.viewCariProker(); //harus dikasih try catch
//                Iterator listproker = cari.iterator();
//                //            System.out.println("size: " + prokerAll.size()); //ok
//                int i = 0;
//                if (i < cari.size()) {
//                    Proker eachproker;
//                    eachproker = (Proker) listproker.next();
//                    atributproker[0] = eachproker.getDosenPenanggung();
//                    atributproker[1] = eachproker.getUraianProker();
//                    atributproker[2] = eachproker.getStatusProker();
//                    atributproker[3] = eachproker.getAnggaranDana();
//                    atributproker[4] = eachproker.getTglperencanaan();
//
//                    tabelproker.addRow(atributproker);
//                    i++;
//                }else{
//                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan!!");}
//
//            } catch (Exception ex) {
//                System.out.println(ex.getMessage());
//            }
//            jTbl_Proker.setModel(tabelproker);
    }//GEN-LAST:event_idprokerKeyPressed

    private void jTbl_RealisasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_RealisasiMouseClicked

        int number = jTbl_Realisasi.getSelectedRow();
        idrealisasi.setText(jTbl_Realisasi.getValueAt(number, 0).toString());
        //        lb_iduser.setText(jTbl_Realisasi.getValueAt(number, 1).toString());
        idproker.setText(jTbl_Realisasi.getValueAt(number, 2).toString());
        try {
            DefaultTableModel model = (DefaultTableModel) jTbl_Realisasi.getModel();
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(number, 3));
            jdatetanggal.setDate(date);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        anggaran.setText(jTbl_Realisasi.getValueAt(number, 4).toString());
        deskripsi.setText(jTbl_Realisasi.getValueAt(number, 5).toString());
    }//GEN-LAST:event_jTbl_RealisasiMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String format = "yyyy-MM-dd";
        SimpleDateFormat date = new SimpleDateFormat(format);
        Realisasi real = new Realisasi();
        Proker proker = new Proker();

        proker.setIdProker(Integer.parseInt(idproker.getText()));
        real.setIdLaporan(Integer.parseInt(idrealisasi.getText()));
        real.setTglRealisasi(String.valueOf(date.format(jdatetanggal.getDate())));
        real.setAnggaran(Double.parseDouble(anggaran.getText()));
        //real.setStatus((String) cb_status.getSelectedItem());
        real.setDeskripsiLaporan(deskripsi.getText());

        try {
            real.insertDb();
            updateUserProkertoRealisasi();
            refreshtabel();
            //refreshtabelhistory();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());;
        }

        idproker.setText("");
        jdatetanggal.setCalendar(null);
        anggaran.setText("");
        deskripsi.setText("");

    }//GEN-LAST:event_saveActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try {
            editRealisasi();
            refreshtabel();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        Realisasi real = new Realisasi();
        real.setIdLaporan(Integer.parseInt(idrealisasi.getText()));
        try {
            real.hapusRealisasi();
            refreshtabel();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_deleteActionPerformed

    private void button_DataProkerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_DataProkerMouseEntered
        panelDataProker.setBackground(new Color(0, 0, 51));
    }//GEN-LAST:event_button_DataProkerMouseEntered

    private void button_DataProkerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_DataProkerMouseExited
        panelDataProker.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_button_DataProkerMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            //refreshtabelproker();
            refreshtabel();

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void txt_cariprokerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariprokerKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariprokerKeyPressed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed

        try {
            refreshtabelproker();
            //cariproker();

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_viewallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewallActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTbl_Proker1.getModel();
        while (model.getRowCount() > 0) {
            model.setRowCount(0);
        }
        tampilprokerstatus();
    }//GEN-LAST:event_btn_viewallActionPerformed

    private void delete_info_akunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_info_akunActionPerformed
        Dosen dosen = new Dosen();
        dosen.setIdDosen(Integer.parseInt(id_dosen.getText()));
        dosen.setIdUser(Integer.parseInt(lb_iduser.getText()));
        try {
            int pilih = JOptionPane.showOptionDialog(this, "Apakah ingin dihapus ?", "Pesan", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if (pilih == JOptionPane.YES_OPTION) {
                dosen.hapusdosen();
                dosen.hapususer();
                this.dispose();
                Login login = new Login();
                login.setVisible(true);
                JOptionPane.showMessageDialog(null, "Berhasil dihapus!!");
                id_dosen.setText("");
                nama_dosen.setText("");
                npp.setText("");
                ttl.setText("");
                agama.setText("");
                jekel.setText("");
                username.setText("");
                pass.setText("");
            } else {

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal hapus akun, karena akun terdaftar di realisasi !!");
            System.out.println(ex.getMessage());
        }


    }//GEN-LAST:event_delete_info_akunActionPerformed

    private void edit_info_akunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_info_akunActionPerformed
        try {
            editdosen();
            edituser();
            JOptionPane.showMessageDialog(null, "Berhasil diedit!!");
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_edit_info_akunActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        Cetak cetak = new Cetak();
        cetak.setVisible(true);
//        this.setVisible(true);

//JOptionPane.showMessageDialog(null, "Dalam tahap pengambangan !!");\
//        MessageFormat header = new MessageFormat("Data Realisasi Proker");
//        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
// 
//        try{
//            jTbl_Realisasi.print(JTable.PrintMode.FIT_WIDTH, header, footer);
//        }
//        catch (java.awt.print.PrinterException e){
//        System.err.format("Cannot print %s%n", e.getMessage());
//                }

    }//GEN-LAST:event_btn_cetakActionPerformed

    private void btn_printpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printpActionPerformed
        MessageFormat header2 = new MessageFormat("Data Pengajuan Proker");
        MessageFormat footer2 = new MessageFormat("Page{0,number,integer}");
        try {

            jTbl_Proker1.print(JTable.PrintMode.FIT_WIDTH, header2, footer2);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btn_printpActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        cariproker();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_shortingprodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_shortingprodiActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTbl_Realisasi.getModel();
        while (model.getRowCount() > 0) {
            model.setRowCount(0);
        }
        carirealprodi();
    }//GEN-LAST:event_btn_shortingprodiActionPerformed

    private void LOGOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOMouseClicked
        panelSelamatDatang.setVisible(true);
        prodi_Realisasi.setVisible(false);
        User_Info.setVisible(false);
        prodi_proker.setVisible(false);

    }//GEN-LAST:event_LOGOMouseClicked

    private void jTbl_ProkerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_ProkerMouseClicked
        int number = jTbl_Proker.getSelectedRow();
        idproker.setText(jTbl_Proker.getValueAt(number, 0).toString());
//        lbl_dsn.setText(jTbl_Proker.getValueAt(number, 1).toString());
//        lbl_uraian.setText(jTbl_Proker.getValueAt(number, 2).toString());
//        lbl_status.setText(jTbl_Proker.getValueAt(number, 3).toString());
//        lbl_anggaran.setText(jTbl_Proker.getValueAt(number, 4).toString());
//        lbl_tanggal.setText(jTbl_Proker.getValueAt(number, 5).toString());

    }//GEN-LAST:event_jTbl_ProkerMouseClicked

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        try {
            refreshtabel();
        } catch (Exception ex) {
            Logger.getLogger(Menu_Prodi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void BTN_cariprokerperiodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_cariprokerperiodeActionPerformed
        cariprokerperiode();
    }//GEN-LAST:event_BTN_cariprokerperiodeActionPerformed

    private void BTN_carirealperiodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_carirealperiodeActionPerformed
       carirealisasiperiode();
    }//GEN-LAST:event_BTN_carirealperiodeActionPerformed

    public void cariproker() {

        Proker proker = new Proker();
        proker.setIdProker(Integer.parseInt(txt_cariproker.getText()));
        DefaultTableModel tabelproker = (DefaultTableModel) jTbl_Proker1.getModel();
        Object[] atributproker = new Object[6];

        try {//eksekusi proker
            ArrayList cari = proker.viewCariProker2(); //harus dikasih try catch
            Iterator listproker = cari.iterator();
            //            System.out.println("size: " + prokerAll.size()); //ok
            int i = 0;
            if (i < cari.size()) {
                Proker eachproker;
                eachproker = (Proker) listproker.next();
                atributproker[0] = eachproker.getIdProker();
                atributproker[1] = eachproker.getDosenPenanggung();
                atributproker[2] = eachproker.getUraianProker();
                atributproker[3] = eachproker.getStatusProker();
                atributproker[4] = eachproker.getAnggaranDana();
                atributproker[5] = eachproker.getTglperencanaan();

                tabelproker.addRow(atributproker);
                i++;
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan!!");
            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        jTbl_Proker1.setModel(tabelproker);

    }

    public void tampilproker() {
        DefaultTableModel model = (DefaultTableModel) jTbl_Proker.getModel();
        while (model.getRowCount() > 0) {
            model.setRowCount(0);
        }

        Proker proker = new Proker();
        DefaultTableModel tabelproker = (DefaultTableModel) jTbl_Proker.getModel();
        Object[] atributproker = new Object[6];

        try {//eksekusi proker
            ArrayList cari = proker.viewProkerApprove(); //harus dikasih try catch
            Iterator listproker = cari.iterator();
            //            System.out.println("size: " + prokerAll.size()); //ok
            int i = 0;
            while (i < cari.size()) {
                Proker eachproker;
                eachproker = (Proker) listproker.next();
                atributproker[0] = eachproker.getIdProker();
                atributproker[1] = eachproker.getDosenPenanggung();
                atributproker[2] = eachproker.getUraianProker();
                atributproker[3] = eachproker.getStatusProker();
                atributproker[4] = eachproker.getAnggaranDana();
                atributproker[5] = eachproker.getTglperencanaan();

                tabelproker.addRow(atributproker);
                i++;
            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        jTbl_Proker.setModel(tabelproker);

    }

    public void tampilprokerstatus() {

        Proker proker = new Proker();
        DefaultTableModel tabelproker = (DefaultTableModel) jTbl_Proker1.getModel();
        Object[] atributproker = new Object[6];

        try {//eksekusi proker
            ArrayList cari = proker.viewProkerRejectnProsess(); //harus dikasih try catch
            Iterator listproker = cari.iterator();
            //            System.out.println("size: " + prokerAll.size()); //ok
            int i = 0;
            while (i < cari.size()) {
                Proker eachproker;
                eachproker = (Proker) listproker.next();
                atributproker[0] = eachproker.getIdProker();
                atributproker[1] = eachproker.getDosenPenanggung();
                atributproker[2] = eachproker.getUraianProker();
                atributproker[3] = eachproker.getStatusProker();
                atributproker[4] = eachproker.getAnggaranDana();
                atributproker[5] = eachproker.getTglperencanaan();

                tabelproker.addRow(atributproker);
                i++;
            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        jTbl_Proker1.setModel(tabelproker);

    }

    public void tampildosen() {
        try {
            String query = "select * from dosen where idDosen='" + lb_iduser.getText() + "'";
            PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                id_dosen.setText(String.valueOf(rs.getInt("idDosen")));
                nama_dosen.setText(rs.getString("nama_dosen"));
                npp.setText(String.valueOf(rs.getInt("NPP")));
                ttl.setText(String.valueOf(rs.getDate("ttl_dosen")));
                agama.setText(rs.getString("agama_dosen"));
                jekel.setText(rs.getString("jenis_kelamin"));
            }

            statement.close();
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }

    public void tampiluserpass() {
        try {
            String query = "select * from user where id_user='" + lb_iduser.getText() + "'";
            PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                username.setText(rs.getString("username"));
                pass.setText(rs.getString("password"));
            }

            statement.close();
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }

    public void editdosen() throws Exception {
        String query = "update dosen set NPP=?, nama_dosen=? , ttl_dosen=?, agama_dosen=?, jenis_kelamin=? where idDosen=?";
        PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query);

        //SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        statement.setString(1, npp.getText());
        statement.setString(2, nama_dosen.getText());
        statement.setString(3, ttl.getText());
        statement.setString(4, agama.getText());
        statement.setString(5, jekel.getText());
        statement.setString(6, id_dosen.getText());
        statement.executeUpdate();
        statement.close();

    }

    public void edituser() throws Exception {
        String query = "update user set username=?, password=? where id_user=?";
        PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query);
        statement.setString(1, username.getText());
        statement.setString(2, pass.getText());
        statement.setString(3, lb_iduser.getText());
        statement.executeUpdate();
        statement.close();

    }

    public void autonumberIdRealisasi() {
        try {
            String query = "SELECT MAX(id_laporan) FROM realisasi"; //Mendapatkan nilai id terakhir
            PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query);
            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
                int a = rs.getInt(1);
                idrealisasi.setText(Integer.toString(a + 1)); //Nilai input yang terakhir ditambahkan 1
            }
            statement.close();
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    public void cariprokerperiode() {
        String format = "yyyy-MM-dd";
        SimpleDateFormat date = new SimpleDateFormat(format);
        String tglawal, tglakhir;
        tglawal = (String.valueOf(date.format(jDate_tglawalproker.getDate())));
        tglakhir = (String.valueOf(date.format(jDate_tglakhirproker.getDate())));

        DefaultTableModel model = (DefaultTableModel) jTbl_Proker.getModel();
        while (model.getRowCount() > 0) {
            model.setRowCount(0);
        }

        Proker proker = new Proker();
        DefaultTableModel tabelproker = (DefaultTableModel) jTbl_Proker.getModel();
        Object[] atributproker = new Object[6];

        try {//eksekusi proker
            String query = "select * from proker where tglperencanaan_proker between '" + tglawal + "' and '" + tglakhir + "' and Status_proker = 'Approved'";
            PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {

                atributproker[0] = rs.getInt("id_proker");
                atributproker[1] = rs.getString("Dosen_penanggung");
                atributproker[2] = rs.getString("uraian_proker");
                atributproker[3] = rs.getString("Status_proker");
                atributproker[4] = rs.getInt("anggaran_dana");
                atributproker[5] = rs.getString("tglperencanaan_proker");

                tabelproker.addRow(atributproker);
            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        jTbl_Proker.setModel(tabelproker);
    }
    public void carirealisasiperiode() {
        String format = "yyyy-MM-dd";
        SimpleDateFormat date = new SimpleDateFormat(format);
        String tglawal, tglakhir;
        tglawal = (String.valueOf(date.format(jDate_tglawalreal.getDate())));
        tglakhir = (String.valueOf(date.format(jDate_tglakhirreal.getDate())));

        DefaultTableModel model = (DefaultTableModel) jTbl_Realisasi.getModel();
        while (model.getRowCount() > 0) {
            model.setRowCount(0);
        }

        Realisasi real = new Realisasi();
        DefaultTableModel tabelrealwadek = (DefaultTableModel) jTbl_Realisasi.getModel();
        Object[] realprodi = new Object[7];

        try {//eksekusi proker
            String query = "select * from realisasi where tglRealisasi between '" + tglawal + "' and '" + tglakhir + "' and Status = 'Approved'";
            PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query);
            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
                realprodi[0] = rs.getInt("id_laporan");
                realprodi[1] = rs.getInt("id_user");
                realprodi[2] = rs.getInt("id_proker");
                realprodi[3] = rs.getString("tglRealisasi");
                realprodi[4] = rs.getDouble("anggaran");
                realprodi[5] = rs.getString("deskripsi_laporan");
                realprodi[6] = rs.getString("Status");

                tabelrealwadek.addRow(realprodi);
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan!!");
            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        jTbl_Realisasi.setModel(tabelrealwadek);

    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Prodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Prodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Prodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Prodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Prodi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_cariprokerperiode;
    private javax.swing.JButton BTN_carirealperiode;
    private javax.swing.JLabel LOGO;
    private javax.swing.JPanel LOGOUT;
    private javax.swing.JLabel LOGOUT_BUTTON;
    private javax.swing.JLabel MenuProdi;
    private javax.swing.JPanel PanelTutup;
    private javax.swing.JPanel PanelUser;
    private javax.swing.JPanel Panel_detailinfo;
    private javax.swing.JLabel SelamatDatang;
    private javax.swing.JPanel User_Info;
    private javax.swing.JTextField agama;
    private javax.swing.JTextField anggaran;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_printp;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_shortingprodi;
    private javax.swing.JButton btn_viewall;
    private javax.swing.JLabel button_DataProker;
    private javax.swing.JLabel button_DataRealisasi;
    private javax.swing.JLabel button_infoUser;
    private javax.swing.JComboBox<String> cb_status;
    private javax.swing.JButton delete;
    private javax.swing.JButton delete_info_akun;
    private javax.swing.JTextArea deskripsi;
    private javax.swing.JLabel di;
    private javax.swing.JButton edit;
    private javax.swing.JButton edit_info_akun;
    private javax.swing.JTextField id_dosen;
    private javax.swing.JTextField idproker;
    private javax.swing.JTextField idrealisasi;
    private com.toedter.calendar.JDateChooser jDate_tglakhirproker;
    private com.toedter.calendar.JDateChooser jDate_tglakhirreal;
    private com.toedter.calendar.JDateChooser jDate_tglawalproker;
    private com.toedter.calendar.JDateChooser jDate_tglawalreal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTbl_Proker;
    private javax.swing.JTable jTbl_Proker1;
    private javax.swing.JTable jTbl_Realisasi;
    private com.toedter.calendar.JDateChooser jdatetanggal;
    private javax.swing.JTextField jekel;
    public static final javax.swing.JLabel lb_iduser = new javax.swing.JLabel();
    private javax.swing.JLabel lb_nama;
    private javax.swing.JPanel logoUnitomo;
    private javax.swing.JTextField nama_dosen;
    private javax.swing.JTextField npp;
    private javax.swing.JPanel panelDataProker;
    private javax.swing.JPanel panelDataRealisasi1;
    private javax.swing.JPanel panelMENU;
    private javax.swing.JPanel panelSelamatDatang;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JPanel panelisi;
    private javax.swing.JTextField pass;
    private javax.swing.JPanel prodi_Realisasi;
    private javax.swing.JPanel prodi_proker;
    private javax.swing.JButton save;
    private javax.swing.JTextField ttl;
    private javax.swing.JTextField txt_cariproker;
    private javax.swing.JTextField txt_realprodi;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
