/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package realisasiprokerGUI;

import java.text.SimpleDateFormat;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import realisasiproker.DatabaseMySQL;
import realisasiproker.User;
import realisasiproker.Dosen;
import realisasiproker.Jabatan;

/**
 *
 * @author VINORIOUS
 */
public class RegsiterForm extends javax.swing.JFrame {
    

    /**
     * Creates new form Dosen
     */
    int Mx,My;
    public RegsiterForm() {
        initComponents();
        autonumberIdUSER();
        autonumberIdDOSEN();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txt_kodedosen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_kodejabatan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_npp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_namadosen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        txt_username = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jdate_tgl = new com.toedter.calendar.JDateChooser();
        txt_passw = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        cb_jekel = new javax.swing.JComboBox<>();
        cb_agama = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        txt_kodeuser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jSeparator1.setFocusable(true);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 160, 50));

        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jSeparator2.setFocusable(true);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 160, 50));

        jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jSeparator3.setFocusable(true);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 160, 50));

        jSeparator4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jSeparator4.setFocusable(true);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 160, 50));

        jSeparator5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jSeparator5.setFocusable(true);
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 160, 50));

        jSeparator6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jSeparator6.setFocusable(true);
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 160, 50));

        jSeparator7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jSeparator7.setFocusable(true);
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 160, 50));

        jSeparator8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jSeparator8.setFocusable(true);
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 160, 50));

        jSeparator9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jSeparator9.setFocusable(true);
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 160, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Passoword    :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, -1, -1));

        txt_kodedosen.setBackground(new java.awt.Color(0, 0, 51));
        txt_kodedosen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_kodedosen.setForeground(new java.awt.Color(255, 255, 255));
        txt_kodedosen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_kodedosen.setFocusable(false);
        txt_kodedosen.setRequestFocusEnabled(false);
        getContentPane().add(txt_kodedosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 160, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kode Dosen  :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        txt_kodejabatan.setBackground(new java.awt.Color(0, 0, 51));
        txt_kodejabatan.setForeground(new java.awt.Color(255, 255, 255));
        txt_kodejabatan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(txt_kodejabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 160, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kode Jabatan:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        txt_npp.setBackground(new java.awt.Color(0, 0, 51));
        txt_npp.setForeground(new java.awt.Color(255, 255, 255));
        txt_npp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(txt_npp, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 160, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NPP             :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        txt_namadosen.setBackground(new java.awt.Color(0, 0, 51));
        txt_namadosen.setForeground(new java.awt.Color(255, 255, 255));
        txt_namadosen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(txt_namadosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 160, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama Dosen :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tanggal Lahir :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Agama         :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        btn_simpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 270, 30));

        txt_username.setBackground(new java.awt.Color(0, 0, 51));
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jenis Kelamin :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Username    :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, -1, -1));

        jdate_tgl.setBackground(new java.awt.Color(0, 0, 51));
        jdate_tgl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jdate_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 160, 30));

        txt_passw.setBackground(new java.awt.Color(0, 0, 51));
        txt_passw.setForeground(new java.awt.Color(255, 255, 255));
        txt_passw.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(txt_passw, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 160, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("X");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 30, 20));

        cb_jekel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan", "Lainnya.." }));
        cb_jekel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(cb_jekel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 160, 30));

        cb_agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Hindu", "Budha", "Konghucu", "Lainnya.." }));
        getContentPane().add(cb_agama, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 160, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("?");
        jLabel1.setToolTipText("Kode : 1 = Wadek, 2 =  Prodi");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 20, -1));

        background.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/realisasiprokerGUI/image/REGISTERNEW.png"))); // NOI18N
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundMouseDragged(evt);
            }
        });
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMousePressed(evt);
            }
        });
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 630));

        txt_kodeuser.setEnabled(false);
        getContentPane().add(txt_kodeuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kode User :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        setSize(new java.awt.Dimension(749, 624));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        String format="yyyy-MM-dd";
        SimpleDateFormat date= new SimpleDateFormat(format);
        Dosen dosen = new Dosen();
        Jabatan jbt= new Jabatan();
        User usr = new User();
        Login log = new Login();
        
        //inheritance
        dosen.setIdUser(Integer.parseInt(txt_kodeuser.getText()));
        
        dosen.setIdDosen(Integer.parseInt(txt_kodedosen.getText()));
        jbt.setIdJabatan(Integer.parseInt(txt_kodejabatan.getText()));
        dosen.setNpp(Double.parseDouble(txt_npp.getText()));
        dosen.setNamaDosen(txt_namadosen.getText());
        dosen.setTtlDosen(String.valueOf(date.format(jdate_tgl.getDate())));
        dosen.setAgamaDosen(cb_agama.getSelectedItem().toString());
        dosen.setJenisKelamin(cb_jekel.getSelectedItem().toString());
        //inheritance
        dosen.setUsername(txt_username.getText());
        dosen.setPassword(txt_passw.getText());

        
        try {
            dosen.inputDosen();
            dosen.inputUser();
            updateDosen();
            updateUser();
            JOptionPane.showMessageDialog(null, "Berhasil Disimpan, Silahkan Login");
           
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Mohon data diisi dengan benar!!"); 
            this.setVisible(true);
            //System.out.println(ex.getMessage());
        }
        
        log.setVisible(true);
        this.dispose();
        
     
        
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMousePressed
        Mx = evt.getX();
        My = evt.getY();
    }//GEN-LAST:event_backgroundMousePressed

    private void backgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - Mx, y - My);
    }//GEN-LAST:event_backgroundMouseDragged

    public void updateDosen() throws Exception {
        String query = "update dosen set id_user=? ,idJabatan=? where idDosen=? ";
        PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query);
        statement.setString(1, txt_kodeuser.getText());
        statement.setString(2, txt_kodejabatan.getText());
        statement.setString(3, txt_kodedosen.getText());
        statement.executeUpdate();
        statement.close();

    }
    
     public void updateUser() throws Exception {
        String query2 = "update user set idJabatan=?  where id_user=? ";
        PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query2);
        statement.setString(1, txt_kodejabatan.getText());
        statement.setString(2, txt_kodeuser.getText());
        statement.executeUpdate();
        statement.close();

    }
     
    public void autonumberIdUSER() {
        try {
            String query = "SELECT MAX(id_user) FROM user"; //Mendapatkan nilai id terakhir
            PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query);
            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
                int a = rs.getInt(1);
                txt_kodeuser.setText(Integer.toString(a + 1)); //Nilai input yang terakhir ditambahkan 1
            }
            statement.close();
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    
    public void autonumberIdDOSEN() {
        try {
            String query = "SELECT MAX(idDosen) FROM dosen"; //Mendapatkan nilai id terakhir
            PreparedStatement statement = DatabaseMySQL.getConnection().prepareStatement(query);
            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
                int a = rs.getInt(1);
                txt_kodedosen.setText(Integer.toString(a + 1)); //Nilai input yang terakhir ditambahkan 1
            }
            statement.close();
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegsiterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cb_agama;
    private javax.swing.JComboBox<String> cb_jekel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private com.toedter.calendar.JDateChooser jdate_tgl;
    private javax.swing.JTextField txt_kodedosen;
    private javax.swing.JTextField txt_kodejabatan;
    private javax.swing.JTextField txt_kodeuser;
    private javax.swing.JTextField txt_namadosen;
    private javax.swing.JTextField txt_npp;
    private javax.swing.JPasswordField txt_passw;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
